weather_o_complex/weather/urls.py
from django.urls import path
from . import views

app_name = "weather"

urlpatterns = [
    path("", views.input_city, name="input_city"),
    path("weather/<str:city>/", views.weather, name="weather"),
    path('city-statistics/', views.city_statistics, name='city_statistics'),

]

weather_o_complex/weather_o_complex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("weather.urls", namespace="weather")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

weather_o_complex/weather/models.py
from django.db import models
from django.contrib.auth.models import User


class SearchHistory(models.Model):
    ip_address = models.GenericIPAddressField(default='0.0.0.0')
    city = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.city} searched at {self.timestamp} from IP {self.ip_address}"


class CitySearchCount(models.Model):
    city = models.CharField(max_length=100, unique=True)
    count = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.city} - {self.count}"

weather_o_complex/weather/forms.py
from dal import autocomplete
from django import forms

class CityForm(forms.Form):
    city = forms.CharField(
        label='Город',
    )

weather_o_complex/weather/views.py
import requests
from django.shortcuts import render, redirect
from .forms import CityForm
from urllib.parse import quote,unquote
from django.http import JsonResponse
from .models import CitySearchCount, SearchHistory
from django.utils.timezone import now
import json
from django.http import HttpResponse

def get_coordinates(city):
    url = f"https://nominatim.openstreetmap.org/search?q={city}&format=json&limit=1"
    headers = {"User-Agent": "weather_o_complex/1.0 (test@example.com)"}
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        data = response.json()
        if data:
            return data[0]["lat"], data[0]["lon"]
        else:
            return None, None
    except requests.exceptions.RequestException as e:
        print(f"Error fetching coordinates: {e}")
        return None, None


def get_weather(lat, lon):
    lat, lon = float(lat), float(lon)

    if lat > 90 or lat < -90 or lon > 180 or lon < -180:
        return None

    url = "https://api.open-meteo.com/v1/forecast"
    headers = {"Content-Type": "application/json"}
    params = {
        "latitude": lat,
        "longitude": lon,
        "current": [
            "temperature_2m",
            "relative_humidity_2m",
            "apparent_temperature",
            "is_day",
            "precipitation",
            "rain",
            "showers",
            "snowfall",
            "weather_code",
            "cloud_cover",
            "pressure_msl",
            "surface_pressure",
            "wind_speed_10m",
            "wind_direction_10m",
            "wind_gusts_10m",
        ],
        "timezone": "Europe/Moscow",
    }
    try:
        response = requests.get(url, headers=headers, params=params)
        response.raise_for_status()
        data = response.json()
        return data
    except requests.exceptions.RequestException as e:
        print(f"Error fetching weather data: {e}")
        return None


def input_city(request):
    last_searched_city = request.COOKIES.get("last_city", None)

    if last_searched_city:
        last_searched_city = unquote(last_searched_city)

    if request.method == "POST":
        form = CityForm(request.POST)
        if form.is_valid():
            city = form.cleaned_data["city"]

            SearchHistory.objects.create(
                city=city,
                ip_address=request.META.get('REMOTE_ADDR', '0.0.0.0')
            )

            city_count, created = CitySearchCount.objects.get_or_create(city=city)
            city_count.count += 1
            city_count.save()

            response = redirect("weather:weather", city=city)
            response.set_cookie(
                "last_city", quote(city), max_age=30 * 24 * 60 * 60
            )
            return response
    else:
        form = CityForm()
    return render(
        request,
        "weather/input_city.html",
        {"form": form, "last_city": last_searched_city},
    )


def weather(request, city):
    lat, lon = get_coordinates(city)
    if lat is not None and lon is not None:
        weather_data = get_weather(lat, lon)
        if weather_data:
            context = {"weather_data": weather_data, "city": city,'lat':lat,'lon':lon}
            return render(request, "weather/weather.html", context)
    context = {
        "message": "Не удалось получить данные о погоде. Пожалуйста, попробуйте позже."
    }
    return render(request, "weather/error.html", context)

def city_statistics(request):
    city_counts = CitySearchCount.objects.all()
    data = {city.city: city.count for city in city_counts}
    json_data = json.dumps(data, indent=4, ensure_ascii=False)
    return HttpResponse(json_data, content_type='application/json')

weather_o_complex/weather/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather App</title>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

weather_o_complex/weather/templates/weather/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ошибка</title>
</head>
<body>
    <h1>Произошла ошибка</h1>
    <p>Извините, произошла ошибка при загрузке страницы.</p>
    <p>Вероятно вы попали сюда, потому что ввели неправильный город</p>
    <a href="{% url 'weather:input_city' %}" class="btn btn-primary btn-back">Вернуться к поиску</a>

</body>
</html>

weather_o_complex/weather/templates/weather/input_city.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Введите город</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'weather/css/style_weather.css' %}" rel="stylesheet">

</head>
<body>
    <div class="form-container">
        <div class="color-block blue">
            <h2>Введите город</h2>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-custom">Получить погоду</button>
        </form>
        {% if last_city %}
            <p>Вы ранее смотрели погоду в городе <a href="{% url 'weather:weather' city=last_city %}">{{ last_city }}</a>.</p>
        {% endif %}
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

weather_o_complex/weather/templates/weather/weather.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Погода в городе {{ city }}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'weather/css/style_weather.css' %}" rel="stylesheet">
</head>
<body>
    <div class="weather-container">
        <div class="color-block blue">
            <h1>Погода в городе {{ city }}</h1>
            <h3>Координаты чтобы вы могли убедиться сами:</h3>
            <h4>Широта: {{ lat }}</h4>
            <h4>Долгота: {{ lon }}</h4>
        </div>
        <div class="color-block green">
            <h2>Текущая погода:</h2>
            <p>Текущая температура: {{ weather_data.current.temperature_2m }} °C</p>
            <p>Относительная влажность: {{ weather_data.current.relative_humidity_2m }} %</p>
            <p>Ощущаемая температура: {{ weather_data.current.apparent_temperature }} °C</p>
            <p>Осадки: {{ weather_data.current.precipitation }} мм</p>
            <p>Дождь: {{ weather_data.current.rain }} мм</p>
            <p>Ливни: {{ weather_data.current.showers }} мм</p>
            <p>Снегопад: {{ weather_data.current.snowfall }} мм</p>
            <p>Облачность: {{ weather_data.current.cloud_cover }} %</p>
            <p>Давление на уровне моря: {{ weather_data.current.pressure_msl }} гПа</p>
            <p>Поверхностное давление: {{ weather_data.current.surface_pressure }} гПа</p>
            <p>Скорость ветра: {{ weather_data.current.wind_speed_10m }} м/с</p>
            <p>Направление ветра: {{ weather_data.current.wind_direction_10m }}°</p>
            <p>Порывы ветра: {{ weather_data.current.wind_gusts_10m }} м/с</p>
        </div>
        <a href="{% url 'weather:input_city' %}" class="btn btn-primary btn-back">Вернуться к поиску</a>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>